CREATE TABLE IF NOT EXISTS courses
(
    CID INTEGER PRIMARY KEY,
    CRN INTEGER,
    SUBJECT TEXT,
    COURSE TEXT,
    SECTION TEXT,
    CAMPUS TEXT,
    CREDITS REAL,
    TITLE TEXT,
    WEEKDAYS TEXT,
    START_TIME TEXT,
    END_TIME TEXT,
    CLASS_MAX INTEGER,
    CLASS_CURRENT INTEGER,
    INSTRUCTOR TEXT,
    START_DATE TEXT,
    END_DATE TEXT,
    LOCATION TEXT,
    MISC TEXT
);
